import { Photo } from '@/types';

export const SAMPLE_PHOTOS: Photo[] = [
  {
    id: '1',
    title: 'Mountain Sunrise',
    description: 'Golden hour over snow-capped mountain peaks',
    imageUrl: '/images/mountain-sunrise.jpg',
    thumbnailUrl: '/images/mountain-sunrise-thumb.jpg',
    category: 'landscape',
    tags: ['mountain', 'sunrise', 'nature', 'landscape'],
    date: '2025-12-15',
    width: 4000,
    height: 2667,
    featured: true,
    price: 45,
    licensingAvailable: true,
  },
  {
    id: '2',
    title: 'Forest Path',
    description: 'Serene pathway through dense forest',
    imageUrl: '/images/forest-path.jpg',
    thumbnailUrl: '/images/forest-path-thumb.jpg',
    category: 'nature',
    tags: ['forest', 'trees', 'nature', 'green'],
    date: '2025-12-10',
    width: 4000,
    height: 2667,
    featured: true,
    price: 40,
    licensingAvailable: true,
  },
  {
    id: '3',
    title: 'Urban Architecture',
    description: 'Modern building geometry and lines',
    imageUrl: '/images/architecture.jpg',
    thumbnailUrl: '/images/architecture-thumb.jpg',
    category: 'architecture',
    tags: ['architecture', 'building', 'urban', 'modern'],
    date: '2025-12-05',
    width: 3600,
    height: 4800,
    featured: false,
    price: 35,
    licensingAvailable: true,
  },
  {
    id: '4',
    title: 'Ocean Waves',
    description: 'Dramatic waves crashing on rocky shore',
    imageUrl: '/images/ocean-waves.jpg',
    thumbnailUrl: '/images/ocean-waves-thumb.jpg',
    category: 'landscape',
    tags: ['ocean', 'waves', 'beach', 'seascape'],
    date: '2025-11-28',
    width: 4000,
    height: 2667,
    featured: true,
    price: 50,
    licensingAvailable: true,
  },
  {
    id: '5',
    title: 'Wildlife Portrait',
    description: 'Close-up of majestic eagle in flight',
    imageUrl: '/images/eagle-flight.jpg',
    thumbnailUrl: '/images/eagle-flight-thumb.jpg',
    category: 'wildlife',
    tags: ['wildlife', 'bird', 'eagle', 'nature'],
    date: '2025-11-20',
    width: 3600,
    height: 4800,
    featured: false,
    price: 55,
    licensingAvailable: true,
  },
  {
    id: '6',
    title: 'City at Night',
    description: 'Vibrant cityscape with neon lights',
    imageUrl: '/images/city-night.jpg',
    thumbnailUrl: '/images/city-night-thumb.jpg',
    category: 'street',
    tags: ['city', 'night', 'urban', 'lights'],
    date: '2025-11-15',
    width: 4000,
    height: 2667,
    featured: false,
    price: 45,
    licensingAvailable: true,
  },
];

export const PHOTO_CATEGORIES: Record<string, string> = {
  landscape: 'Landscape',
  portrait: 'Portrait',
  wildlife: 'Wildlife',
  architecture: 'Architecture',
  nature: 'Nature',
  street: 'Street',
  other: 'Other',
};

export const LICENSE_TIERS = [
  {
    id: 'personal',
    name: 'Personal Use License',
    description: 'For personal, non-commercial projects',
    price: 9.99,
    rights: ['Personal use', 'Non-commercial only', 'Attribution required'],
  },
  {
    id: 'commercial',
    name: 'Commercial License',
    description: 'For commercial projects with attribution',
    price: 49.99,
    rights: ['Commercial use', 'Website/social media', 'Attribution required'],
  },
  {
    id: 'extended',
    name: 'Extended Commercial License',
    description: 'Full commercial rights without attribution',
    price: 99.99,
    rights: ['Commercial use', 'No attribution needed', 'Marketing use'],
  },
  {
    id: 'exclusive',
    name: 'Exclusive License',
    description: 'Exclusive rights to single buyer',
    price: 299.99,
    rights: ['Full exclusive rights', 'No other sales', 'Complete ownership'],
  },
];

export const PRODUCT_TIERS = [
  {
    id: 'web',
    name: 'Web-Optimized Download',
    price: 4.99,
    description: 'Perfect for web use (72 DPI, JPG)',
    downloadResolution: '2000x1333',
  },
  {
    id: 'full',
    name: 'Full Resolution Download',
    price: 19.99,
    description: 'High-resolution for printing (300 DPI, TIFF)',
    downloadResolution: '4000x2667',
  },
  {
    id: 'raw',
    name: 'RAW File (Original)',
    price: 39.99,
    description: 'Unedited original camera file (.NEF/.CR2)',
    downloadResolution: 'Original format',
  },
];
